### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rraallvv** [kodaxx/spark-payments-dash-webpack#2]
Is there a license attached to the project? Keep up the good work.

**Comment by kodaxx** [comment]
Yes, several versions ago this work is changed licenses and is currently
licensed under GNU AGPLv3. A license file has been added to reflect this

**Comment by rraallvv** [comment]
Thanks for the quick reply. It's very much appreciated.

**Comment by kodaxx** [comment]
No problem. Anything else I can help with, please let me know.
